In [1]:
"""
-----------------(Brief informations)--------------------#
-- This script is a step by step approach in completing the taks 1 (Web scraping) project CodeAlpha intenship program
"""

'\n-----------------(Brief informations)--------------------#\n-- This script is a step by step approach in completing the taks 1 (Web scraping) project CodeAlpha intenship program\n'

In [2]:
# Install the Python libraries
# pip install requests beautifulsoup4 pandas

In [3]:
# Make our first request
import requests
from bs4 import BeautifulSoup as BS
url = "https://books.toscrape.com/"
response = requests.get(url)

print(response.status_code)

200

In [4]:
"""
Finding the books, 
for example
<article class="product_pod">
"""

'\nFinding the books, \nfor example\n<article class="product_pod">\n'

In [5]:
soup = BS(response.text, "html.parser")

print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [6]:
books = soup.find_all("article", class_="product_pod")

print(len(books))

20

In [7]:
# Finding element element using Beautifulsoup(BS)

# Extract the title
first_book = books[0]
title = first_book.h3.a["title"]

print(title)

#Extract the price
price = first_book.find("p", class_="price_color").text

print(price)

"""
Extracting the rating
The rating is stored as a CSS class.

For example:
<p class="star-rating Three">
"""
rating = first_book.find("p", class_="star-rating")["class"][1]

print(rating)



print(f"The First book is : {title}, and Price is {price}, with '{rating}' Rating")

A Light in the Attic
Â£51.77
Three
The First book is : A Light in the Attic, and Price is Â£51.77, with 'Three' Rating

In [8]:
# Extract availability
availability = first_book.find(
    "p", class_="instock availability"
).text.strip()

print(availability)

In stock

In [9]:

#Put everything together

#Extracting every book on the page.

import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

for book in books:

    title = book.h3.a["title"]

    price = book.find(
        "p", class_="price_color"
    ).text

    rating = book.find(
        "p", class_="star-rating"
    )["class"][1]

    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()



"""
Storing the data

Printing the information isn't enough. We need to turn it into a dataset that we can analyze later.
"""

books_data = []

for book in books:

    title = book.h3.a["title"]

    price = book.find(
        "p", class_="price_color"
    ).text

    rating = book.find(
        "p", class_="star-rating"
    )["class"][1]

    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()

    books_data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    })

# Display all books

    #print(title)
    #print(price)
    #print(rating)
    #print(availability)
    #print("-" * 50)
    
# confirm if its saved to book_data
     #print(books_data[:2])

"""
Converting it to Pandas
(turning the list into a proper DataFrame.)
"""

import pandas as pd

books_data_df = pd.DataFrame(books_data)

In [10]:
# Displaying The Dataframe (top 5)
books_data_df.head()

# Check the dataset shape
books_data_df.shape

# Check the dataset informations
books_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     str
 1   Price         20 non-null     str
 2   Rating        20 non-null     str
 3   Availability  20 non-null     str
dtypes: str(4)
memory usage: 1.8 KB

In [11]:
# ======= SCRAPING MULTIPLE PAGES =========

""" The webpage consist of many catalogue with differant pages
https://books.toscrape.com/catalogue/page-1.html
https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
...

I will be using python to nagivage through

"""
catalogue_url = "https://books.toscrape.com/catalogue/page-2.html"

response = requests.get(catalogue_url)

#Confirm the status of connection

#print(response.status_code)

#print(len(books))

In [12]:
# ======= SCRAPING MULTIPLE PAGES SUMMARY (i included the books url) =========
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd

books_data_multipage = []

for page in range(1, 51):

    multipage_url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    page_response = requests.get(multipage_url)

    multipage_soup = BS(page_response.text, "html.parser")

    books = multipage_soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]

        price = book.find(
            "p", class_="price_color"
        ).text.strip()

        rating = book.find(
            "p", class_="star-rating"
        )["class"][1]

        availability = book.find(
            "p", class_="instock availability"
        ).text.strip()

        relative_url = book.h3.a["href"]
        product_url = "https://books.toscrape.com/catalogue/"+relative_url

        books_data_multipage.append({
            "Title": title,
            "Price": price,
            "Rating": rating,
            "Availability": availability,
            "URL":  product_url
        })

#print("Total books scraped:", len(books_data_multipage))

In [13]:
# ======= Create Dataframe from the newly scarped Data =========

books_data_multipage_df = pd.DataFrame(books_data_multipage)

# Displaying The Dataframe (top 5)

books_data_multipage_df.head()

# Displaying The Dataframe (last 5)
books_data_multipage_df.tail()

,Title,Price,Rating,Availability,URL
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,One,In stock,https://books.toscrape.com/catalogue/alice-in-...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,Four,In stock,https://books.toscrape.com/catalogue/ajin-demi...
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,Five,In stock,https://books.toscrape.com/catalogue/a-spys-de...
998,1st to Die (Women's Murder Club #1),Â£53.98,One,In stock,https://books.toscrape.com/catalogue/1st-to-di...
999,"1,000 Places to See Before You Die",Â£26.08,Five,In stock,https://books.toscrape.com/catalogue/1000-plac...

In [22]:
#books_data_multipage_df.to_csv("books_dataset.csv", index = False)

#print("dataset saved Suucessfully")

In [24]:
# ======= CLEANING THE DATA =========

# Clean the price column - remove both £ and Â characters
books_data_multipage_df["Price"] = books_data_multipage_df["Price"].str.replace("£", "", regex=False)
books_data_multipage_df["Price"] = books_data_multipage_df["Price"].str.replace("Â", "", regex=False)  # Remove the problematic Unicode character
books_data_multipage_df["Price"] = books_data_multipage_df["Price"].astype(float)

# Checking the price datatype
books_data_multipage_df["Price"].dtype

dtype('float64')

In [25]:
#Checking the price values
books_data_multipage_df.head()

,Title,Price,Rating,Availability,URL
0,A Light in the Attic,51.77,Three,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,One,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,One,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,Four,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,Five,In stock,https://books.toscrape.com/catalogue/sapiens-a...

In [ ]:
#Checking for missing values

books_data_multipage_df.isnull().sum()

In [ ]:
#Checking Duplicate books

books_data_multipage_df.duplicated().sum()

In [ ]:
#Checking for Duplicate Titles

books_data_multipage_df["Title"].duplicated().sum()

In [ ]:
#===== Gross checking ==========
print(books_data_multipage_df.shape)
print(books_data_multipage_df.isnull().sum())
print(books_data_multipage_df.duplicated().sum())
books_data_multipage_df["Title"].duplicated().sum()

In [ ]:
# locating the duplicate Title 

"""
Why am i checking this?
A duplicate title doesn't necessarily mean a duplicate record.
For example, two rows could have the same title but different:
prices
URLs
ratings
availability
If the entire rows are identical, then it's a true duplicate and i can remove it.
If the rows differ, i should keep them and investigate why.

so i'm not implimentong the df.drop_duplicates() function
"""

pd.set_option('display.max_rows', 10)
duplicates = books_data_multipage_df[books_data_multipage_df["Title"].duplicated(keep = False)]
print(duplicates["Title"])

In [ ]:
duplicates[["Title", "Price", "Rating", "Availability", "URL"]]

In [ ]:
 books_data_multipage_df.loc[[236, 358]]

In [26]:
#===== Check the final dataset ==========

print("Rows:", len( books_data_multipage_df))
print('-'*40)
print("Columns:", len( books_data_multipage_df.columns))
print('-'*40)
print("Missing values\n", books_data_multipage_df.isnull().sum())
print('-'*40)
print("Data-Types\n", books_data_multipage_df.dtypes)
print('-'*40)
print("Data-Description\n", books_data_multipage_df.describe())
print('-'*40)
print("Data-info",books_data_multipage_df.info())

Rows: 1000
----------------------------------------
Columns: 5
----------------------------------------
Missing values
 Title           0
Price           0
Rating          0
Availability    0
URL             0
dtype: int64
----------------------------------------
Data-Types
 Title               str
Price           float64
Rating              str
Availability        str
URL                 str
dtype: object
----------------------------------------
Data-Description
             Price
count  1000.00000
mean     35.07035
std      14.44669
min      10.00000
25%      22.10750
50%      35.98000
75%      47.45750
max      59.99000
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   str
 1   Price         1000 non-null   float64
 2   Rating        1000 non-null   str
 3   Availability  1000 non-null   str
 4   URL           1000 non-null   str
dtypes: float64(1), str(4)
memory usage: 176.0 KB
Data-info None

In [27]:
#===== Saving the final dataset ==========
books_data_multipage_df.to_csv("books_dataset.csv", index = False)

print("Final Dataset saved successfully.")

Final Dataset saved successfully.